# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cb3b95e2a05df14a6682ad969e9cedbf03439b4e78ff93a7ed8de50658a7f3a7a3e1ca4e86e97069c15217c5d854ee4fd6ad792998f50e8e66ea4251ab889b5

test:
  secret_key_base: 49deab5d018f94bc07fb3017665a791b044ece797e6132f3489b7edf868aae5c7783ddd9e215bc32682e1131726c6b2268f85b591ea76774b9c4c8239f555c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
